<a href="https://colab.research.google.com/github/KartonDCP/MathWorks/blob/master/Lab10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Вариант 4
## Разработать, обучить и исследовать нейронную сеть, предназначенную для распознавания 5 символов, представленных в виде матриц `4:5`:
# Символы:
# 1 0 0 1 == K
# 1 0 1 0 
# 1 1 0 0 
# 1 0 1 0 
# 1 0 0 1 
=========
# 1 0 0 1 == H
# 1 0 0 1 
# 1 1 1 1 
# 1 0 0 1 
# 1 0 0 1

# 1 1 1 1 == Г
# 1 0 0 0 
# 1 0 0 0 
# 1 0 0 0 
# 1 0 0 0

# 1 1 1 1 == Е
# 1 0 0 0 
# 1 1 1 1 
# 1 0 0 0 
# 1 1 1 1

# 1 1 1 1 == Г
# 1 0 0 1
# 1 0 0 1 
# 1 0 0 1 
# 1 1 1 1



In [577]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras as keras
from tensorflow.keras import regularizers

In [578]:
K = [[1, 0, 0, 1],
     [1, 0, 1, 0],
     [1, 1, 0, 0],
     [1, 0, 1, 0],
     [1, 0, 0, 1]] 

H = [[1, 0, 0, 1],
     [1, 0, 0, 1],
     [1, 1, 1, 1],
     [1, 0, 0, 1],
     [1, 0, 0, 1]] 

G_r = [[1, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0]] 

E = [[1, 1, 1, 1],
     [1, 0, 0, 0],
     [1, 1, 1, 0],
     [1, 0, 0, 0],
     [1, 1, 1, 1]] 

O = [[1, 1, 1, 1],
     [1, 0, 0, 1],
     [1, 0, 0, 1],
     [1, 0, 0, 1],
     [1, 1, 1, 1]] 


In [579]:
dataset_size = 1000
dataset = []

for i in range(dataset_size):
  dataset.append((K, 0.1))
  dataset.append((H, 0.3))
  dataset.append((G_r, 0.5))
  dataset.append((E, 0.7))
  dataset.append((O, 1))

dataset = np.array(dataset)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  # This is added back by InteractiveShellApp.init_path()


In [580]:
dataset

array([[list([[1, 0, 0, 1], [1, 0, 1, 0], [1, 1, 0, 0], [1, 0, 1, 0], [1, 0, 0, 1]]),
        0.1],
       [list([[1, 0, 0, 1], [1, 0, 0, 1], [1, 1, 1, 1], [1, 0, 0, 1], [1, 0, 0, 1]]),
        0.3],
       [list([[1, 1, 1, 1], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0]]),
        0.5],
       ...,
       [list([[1, 1, 1, 1], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0]]),
        0.5],
       [list([[1, 1, 1, 1], [1, 0, 0, 0], [1, 1, 1, 0], [1, 0, 0, 0], [1, 1, 1, 1]]),
        0.7],
       [list([[1, 1, 1, 1], [1, 0, 0, 1], [1, 0, 0, 1], [1, 0, 0, 1], [1, 1, 1, 1]]),
        1]], dtype=object)

In [581]:
x = np.array([np.array(i[0]).reshape(20,) for i in dataset])
y = np.array([i[1] for i in dataset])

In [582]:
x

array([[1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [583]:
y

array([0.1, 0.3, 0.5, ..., 0.5, 0.7, 1. ])

In [584]:
translate = {
    0.1: "К",
    0.3: "Н",
    0.5: "Г",
    0.7: "Е",
    1: "О",
}

In [585]:
random_value = dataset[55]
print(translate[random_value[1]])
np.array(random_value[0])

К


array([[1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 1]])

In [586]:
model = keras.Sequential([keras.layers.Dense(20, activation='tanh', kernel_regularizer=regularizers.l2(l2=0.005)),
                          keras.layers.Dense(1, activation='tanh')])

In [587]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(),
              metrics=['accuracy'])

In [588]:
model.fit(x, y, epochs=5);

Epoch 1/5
157/157 [==============================] - 1s 4ms/step - loss: 0.7573 - accuracy: 0.1848
Epoch 2/5
157/157 [==============================] - 1s 4ms/step - loss: 0.5615 - accuracy: 0.2000
Epoch 3/5
157/157 [==============================] - 1s 4ms/step - loss: 0.5414 - accuracy: 0.2000
Epoch 4/5
157/157 [==============================] - 1s 4ms/step - loss: 0.5293 - accuracy: 0.2000
Epoch 5/5
157/157 [==============================] - 1s 4ms/step - loss: 0.5209 - accuracy: 0.2000


In [589]:
test_size = 10000
test = []

for i in range(test_size):
  test.append((K, 0.1))
  test.append((H, 0.3))
  test.append((G_r, 0.5))
  test.append((E, 0.7))
  test.append((O, 1))

test = np.array(test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  # This is added back by InteractiveShellApp.init_path()


In [590]:
def output(value, outline_error=0.1):
  for kv in translate.items():
    if np.abs(value - kv[0]) < outline_error:
      return kv[1]

In [591]:
test_x = np.array([np.array(i[0]).reshape(20,) for i in test])
test_y = np.array([i[1] for i in test])

In [592]:
predicted_x = model.predict(test_x)

In [594]:
current_predicts = 0
for i in range(test_size):
  if i % 1003 == 0:
    print(f"{i}) predicted={output(predicted_x[i], 0.1)}, real={translate[test_y[i]]}")
  if output(predicted_x[i], 0.1) == translate[test_y[i]]:
    current_predicts += 1
print(f"Test size: {test_size}, Currect predictions: {current_predicts}")
print(f"Test accuracy: {np.round(current_predicts/test_size*100, 2)}%")

0) predicted=К, real=К
1003) predicted=Е, real=Е
2006) predicted=Н, real=Н
3009) predicted=О, real=О
4012) predicted=Г, real=Г
5015) predicted=К, real=К
6018) predicted=Е, real=Е
7021) predicted=Н, real=Н
8024) predicted=О, real=О
9027) predicted=Г, real=Г
Test size: 10000, Currect predictions: 10000
Test accuracy: 100.0%
