<a href="https://colab.research.google.com/github/KartonDCP/MathWorks/blob/master/Task11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Вариант 5
## Оценка стоимости разработки WEB–страниц. 


In [378]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras as keras
from tensorflow.keras import regularizers

In [379]:
answers = np.array([
           ([1, 0, 0, 0], 10),
           ([0, 0, 0, 0], 1),
           ([1, 1, 0, 0], 30),
           ([1, 1, 1, 0], 80),
           ([1, 1, 0, 1], 100),
           ([1, 1, 1, 1], 300),
]);
answers_dict = {
           str(np.array([1, 0, 0, 0])): 10,
           str(np.array([0, 0, 0, 0])): 1,
           str(np.array([1, 1, 0, 0])): 30,
           str(np.array([1, 1, 1, 0])): 80,
           str(np.array([1, 1, 0, 1])): 100,
           str(np.array([1, 1, 1, 1])): 300,
};

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  import sys


In [380]:
x = np.array([np.array(i[0]) for i in answers])
y = np.array([i[1] for i in answers])
max_y = np.max(y)
y = y/max_y

In [381]:
x

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 1, 0, 1],
       [1, 1, 1, 1]])

In [382]:
y

array([0.03333333, 0.00333333, 0.1       , 0.26666667, 0.33333333,
       1.        ])

In [383]:
model = keras.Sequential([keras.layers.Dense(4, activation='tanh', kernel_regularizer=regularizers.l1_l2(l1=0.0005, l2=0.05)),
                          keras.layers.Dense(20, activation='tanh', kernel_regularizer=regularizers.l1(l1=0.0005)),
                          keras.layers.Dense(1, activation='tanh')])

In [384]:
model.compile(optimizer='adam', metrics=['accuracy'])

In [385]:
model.fit(x, y, epochs=5);

Epoch 1/5
1/1 [==============================] - 0s 350ms/step - loss: 0.1870 - accuracy: 0.0000e+00
Epoch 2/5
1/1 [==============================] - 0s 10ms/step - loss: 0.1863 - accuracy: 0.0000e+00
Epoch 3/5
1/1 [==============================] - 0s 5ms/step - loss: 0.1857 - accuracy: 0.0000e+00
Epoch 4/5
1/1 [==============================] - 0s 7ms/step - loss: 0.1851 - accuracy: 0.0000e+00
Epoch 5/5
1/1 [==============================] - 0s 7ms/step - loss: 0.1844 - accuracy: 0.0000e+00


#Вместо input который тоже есть в питоне, буду использовать просто переменные, тк в Notebook не получиться делать input адекватно, суть никак не измениться

In [386]:
is_visial_cool = 1
is_site_fast = 1
is_site_hard_understand = 1
is_site_reach = 0
x_test = np.array([is_visial_cool, is_site_fast, is_site_hard_understand, is_site_reach])

In [387]:
predicted = model.predict(np.array([x_test])) * max_y # избавимся от нормализации данных умножив на max_y
predicted

array([[90.39575]], dtype=float32)

In [388]:

print(f"predicted cost {predicted[0]}, real is {answers_dict[str(x_test)]}")

predicted cost [90.39575], real is 80


# Мы предсказали значение сайта в 90к $, реально значение 80, можель успешно обучена, несмотря на малый датасет